VendorPortal/VendorPortal/Controllers/HomeController.cs
using VendorPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Xml.Linq;
using System.Xml;
using System.Data.SqlClient;
using System.Text;
using Newtonsoft.Json.Linq;
using System.Collections;
using Newtonsoft.Json;
using System.Net;

/*
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Http.Cors;
using System.Web.Mvc;
*/

namespace VendorPortal.Controllers
{
    public class HomeController : Controller
    {
        BL_DB focus_db = new BL_DB();
        public static string connection = "";
        string PostDCNo="";
        int PostDCDate = 0;
        string PostBillNo = "";
        int PostBillDate = 0;
        int DocDate = 0;
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult PendingOrder()
        {
            ViewBag.Message = "Your application description page.";
            ViewBag.userID = Session["UserID"];

            return View();
        }
        public ActionResult GRNEntry()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult MRNEntry()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Register()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Login(string user_name, string password)
        {
            //return RedirectToAction("Home", "PendingOrder");
            /*
            string strErrorMessage = "";
            string strQuery = "select * from ICS_ProductMap where destination IN ('sName', 'sCode', 'iDefaultBaseUnit__Id', 'ParentId')";
            DataSet ds = focus_db.GetData(strQuery, CompanyId, ref strErrorMessage);

            if (ds.Tables[0].Rows.Count < 4)
            {
                //string error_msg = "Mandatory Fields Not Match!";
                //return Json(new { status = false, data = new { message = error_msg } });
            }
            */


            //string path = Server.MapPath("~/App_Data/somedata.xml");
            string path = Server.MapPath("~/bin/XMLFiles/DBConfig.xml");

            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.Load(path);

            XmlNodeList bookNodes = xmlDoc.SelectNodes("//DatabaseConfig/Database/Data_Source");



            //var xml = XmlDocument.Load(@path);

            //Session["UserID"] = path;
            //Session["UserID"] = xml.ToString();

            //XmlNode node = xmlDoc.SelectSingleNode("xmlRootNode/levelOneChildNode");
            XmlNode node = xmlDoc.SelectSingleNode("DatabaseConfig/Database/Data_Source");
            //string text = node.InnerText;
            string serverName = xmlDoc.SelectSingleNode("DatabaseConfig/Database/Data_Source").InnerText;
            string databaseName = xmlDoc.SelectSingleNode("DatabaseConfig/Database/Initial_Catalog").InnerText;
            string userId = xmlDoc.SelectSingleNode("DatabaseConfig/Database/User_Id").InnerText;
            string Password = xmlDoc.SelectSingleNode("DatabaseConfig/Database/Password").InnerText;

            Session["API_UserName"] = xmlDoc.SelectSingleNode("DatabaseConfig/Database/API_UserName").InnerText;
            Session["API_Password"] = xmlDoc.SelectSingleNode("DatabaseConfig/Database/API_Password").InnerText;
            Session["API_CompanyCode"] = databaseName.Substring(databaseName.Length - 3);


            //Session["UserID"] = serverName + databaseName + userId + password;
            //Session["UserID"] = "session is set";
            //Session["UserID"] = bookNodes.Item(1).Value.ToString();



            var con = "Data Source=" + serverName + ";Initial Catalog=" + databaseName + ";User Id=" + userId + ";Password=" + Password + ";Integrated Security=True;Trusted_Connection=false;";
            connection = "Data Source=" + serverName + ";Initial Catalog=" + databaseName + ";User Id=" + userId + ";Password=" + Password + ";Integrated Security=True;Trusted_Connection=false;";
            string returnData = "";
            bool status = false;
            using (SqlConnection myConnection = new SqlConnection(con))
            {
                string oString = "Select * from ICS_VendorPortal_Login where user_name=@user_name AND password=@password";
                //string oString = "Select * from ICS_VendorPortal_Login where user_name='"+ user_name + "' AND password='"+ password + "'";

                SqlCommand oCmd = new SqlCommand(oString, myConnection);
                oCmd.Parameters.AddWithValue("@user_name", user_name);
                oCmd.Parameters.AddWithValue("@password", password);
                myConnection.Open();
                using (SqlDataReader oReader = oCmd.ExecuteReader())
                {
                    if (oReader.Read())
                    {
                        Session["UserID"] = oReader["party_master_id"];
                        Session["UserName"] = oReader["user_name"];
                        returnData = "Successfully Login";
                        status = true;
                    }
                    else
                    {
                        returnData = "Failed Login";
                    }
                    myConnection.Close();
                }
            }


            return Json(new { status = status, data = new { message = returnData } });
            //return returnData;
        }

        public static string ConvertIntoJson(DataTable dt)
        {
            var jsonString = new StringBuilder();
            if (dt.Rows.Count > 0)
            {
                jsonString.Append("[");
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    jsonString.Append("{");
                    for (int j = 0; j < dt.Columns.Count; j++)
                        jsonString.Append("\"" + dt.Columns[j].ColumnName + "\":\""
                            + dt.Rows[i][j].ToString().Replace('"', '\"') + (j < dt.Columns.Count - 1 ? "\"," : "\""));

                    jsonString.Append(i < dt.Rows.Count - 1 ? "}," : "}");
                }
                return jsonString.Append("]").ToString();
            }
            else
            {
                return "[]";
            }
        }

        [HttpPost]
        public ActionResult FillGRN()
        {
            string json_return = "";
            string sql = "select ICS_VendorPortal_PendPo.*, mCore_Product.sName as item_name, mCore_Department.sName as branch_name, cast(tCore_Indta_0.mRate as decimal(18,3)) as PORate from ICS_VendorPortal_PendPo inner join mCore_Product on mCore_Product.iMasterId = ICS_VendorPortal_PendPo.Item_Id inner join mCore_Department on mCore_Department.iMasterId = ICS_VendorPortal_PendPo.Branch_Id inner join tCore_Indta_0 on ICS_VendorPortal_PendPo.iBodyId=tCore_Indta_0.iBodyId where ICS_VendorPortal_PendPo.User_Id = " + Session["UserID"];
            using (SqlConnection myConnection = new SqlConnection(connection))
            {
                SqlCommand oCmd = new SqlCommand(sql, myConnection);
                myConnection.Open();

                var dataReader = oCmd.ExecuteReader();
                var dataTable = new DataTable();
                dataTable.Load(dataReader);

                json_return = ConvertIntoJson(dataTable);
                myConnection.Close();
            }

            var jsonResult = Json(json_return, "application/json", System.Text.Encoding.UTF8, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpPost]
        public ActionResult FillBranch()
        {
            string json_return = "";
            string sql = "select iMasterId, sName from mCore_Department";
            using (SqlConnection myConnection = new SqlConnection(connection))
            {
                SqlCommand oCmd = new SqlCommand(sql, myConnection);
                myConnection.Open();

                var dataReader = oCmd.ExecuteReader();
                var dataTable = new DataTable();
                dataTable.Load(dataReader);

                json_return = ConvertIntoJson(dataTable);
                myConnection.Close();
            }
            //return JObject.Parse(json_return);
            //return Json(new { status = true, data = new { message = json_return } });


            //var jsonResult = Json(JObject.Parse(json_return), "application/json", System.Text.Encoding.UTF8, JsonRequestBehavior.AllowGet);
            var jsonResult = Json(json_return, "application/json", System.Text.Encoding.UTF8, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }


        [HttpPost]
        public ActionResult FillAccounts()
        {
            string path = Server.MapPath("~/bin/XMLFiles/DBConfig.xml");

            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.Load(path);
           
            XmlNode node = xmlDoc.SelectSingleNode("DatabaseConfig/Database/Data_Source");            
            string serverName = xmlDoc.SelectSingleNode("DatabaseConfig/Database/Data_Source").InnerText;
            string databaseName = xmlDoc.SelectSingleNode("DatabaseConfig/Database/Initial_Catalog").InnerText;

VendorPortal/VendorPortal/Controllers/VendorPortalController.cs
using VendorPortal.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Http.Cors;
using System.Web.Mvc;

namespace VendorPortal.Controllers
{
    public class VendorPortalController : Controller
    {
        // GET: VendorPortal
        public ActionResult Index()
        {
            return View();
        }

        

        public string Login()
        {
            /*
            BL_DB DataAcesslayer = new BL_DB();
            int CompanyId = 122;
            string strErrorMessage = string.Empty;
            string strValue = "";
            strValue = $@"SELECT * FROM ICS_MasterMap";
            clsGeneric.writeLog("Query :" + strValue);
            DataAcesslayer.GetExecute(strValue, CompanyId, ref strErrorMessage);
            if (strErrorMessage != "")
            {
                clsGeneric.writeLog("strErrorMessage :" + strErrorMessage);
            }

            return null;
            */
            //return RedirectToAction("Home", "PendingOrder");
            return "999";
        }
    }
}

VendorPortal/VendorPortal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VendorPortal/VendorPortal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VendorPortal/VendorPortal/Views/Home/GRNEntry.cshtml
@{
    ViewBag.Title = "GRNEntry";
}

<h2>GRN Entry</h2>
<hr />
<div class="container">
    <div class="row" style="padding: 10px;">
        <div class="col-md-6">                             
            <div class="form-group">
                <label class="col-md-2 control-label" for="branch">Branch:</label>
                <div class="col-md-10">
                    <input class="form-control" id="branch" name="branch" type="text" disabled value="" />                    
                </div>
            </div>             
        </div>
    </div>

    <div class="row" style="padding: 10px;">
        <div class="col-md-6">
            <div class="form-group">
                <label class="col-md-2 control-label" for="dc_no">DC No:</label>
                <div class="col-md-10">
                    <input class="form-control" id="dc_no" name="dc_no" type="text" value="" />
                    <span class="field-validation-valid text-danger" data-valmsg-for="Email" data-valmsg-replace="true"></span>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <label class="col-md-2 control-label" for="dc_date">DC Date:</label>
                <div class="col-md-10">
                    <input class="form-control" id="dc_date" name="dc_date" type="date" />
                    <span class="field-validation-valid text-danger" data-valmsg-for="Password" data-valmsg-replace="true"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="padding: 10px;">
        <div class="col-md-6">
            <div class="form-group">
                <label class="col-md-2 control-label" for="bill_no">Bill No:</label>
                <div class="col-md-10">
                    <input class="form-control" id="bill_no" name="bill_no" type="text" value="" />
                    <span class="field-validation-valid text-danger" data-valmsg-for="Email" data-valmsg-replace="true"></span>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <label class="col-md-2 control-label" for="bill_date">Bill Date:</label>
                <div class="col-md-10">
                    <input class="form-control" id="bill_date" name="bill_date" type="date" />
                    <span class="field-validation-valid text-danger" data-valmsg-for="Password" data-valmsg-replace="true"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <table id="grn_table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Sr No</th>                   
                    <th>Item</th>
                    <th>Pending Qty</th>
                    <th>Challan Qty</th>                      
                    <th>PO Rate</th>                      
                    <th>Challan Rate</th>                      
                </tr>
            </thead>
            <tbody id="grnBody">
                <!--<tr>
                    <td>Sr No</td>
                    <td>Item</td>
                    <td>Pending Qty</td>
                    <td><input id="challan" name="challan" type="text" /></td>
                    <td>PO Rate</td>
                    <td><input id="challan" name="challan" type="text" /></td>
                </tr>

                <tr>
                    <td>Sr No</td>
                    <td>Item</td>
                    <td>Pending Qty</td>
                    <td><input id="challan" name="challan" type="text" /></td>
                    <td>PO Rate</td>
                    <td><input id="challan" name="challan" type="text" /></td>
                </tr>
                    -->
            </tbody>
        </table>
    </div>

</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input id="save_grn" type="submit" value="Save GRN" class="btn btn-default" />
    </div>
</div>        

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

@section Scripts {
    <script type="text/javascript">
        var Totalrecord = 0;
        var Processrecord = 0;
        LoadTable();

        $('#save_grn').click(function () {
            GRN_Save();
        });

        function GRN_Save()
        {

            $('.challan').each(function () {
                //$("#" + $(this).attr("arg4")).val()
                //alert($(this).val());
                //alert($("#" + $(this).attr("arg4")).val());
                SaveGRN($(this).attr("arg1"), $(this).attr("arg2"), $(this).attr("arg3"), $(this).val(), $("#" + $(this).attr("arg4")).val())
            });
        }

        function PostGRN()
        {
            $.ajax({
                type: "POST",
                url: "@Url.Action("PostGRN", "Home")",
                data: {
                },
            dataType: "json",
            success: function (response) {
                console.log(response);
                if(response.status === true)
                {
                    alert(response.data.message);
                    document.location = "@Url.Action("PendingOrder", "Home")";
                }
                else
                {
                    alert(response.data.message);
                }

            },
            error: function () {
                alert("An error occurred while updating Database.");
            }
        });
        }

        function SaveGRN(IBody, Pend_Qty, PORate, ChallanQty, ChallanRate)
        {
            console.log(IBody, Pend_Qty, PORate, ChallanQty, ChallanRate);
            //return;
            $.ajax({
                type: "POST",
                url: "@Url.Action("SaveGRN", "Home")",
                data: {
                    DCNo: $("#dc_no").val(),
                    DCDate: $("#dc_date").val(),
                    BillNo: $("#bill_no").val(),
                    BillDate: $("#bill_date").val(),
                    IBody: IBody,
                    Pend_Qty: Pend_Qty,
                    PORate: PORate,
                    ChallanQty: ChallanQty,
                    ChallanRate: ChallanRate
                },
                dataType: "json",
                success: function (response) {
                    // Handle the response from the server
                    console.log(response);
                    //var data = JSON.parse(response);
                    Processrecord++;
                    if (Totalrecord == Processrecord) {
                        //alert("starting to post");
                        PostGRN();
                    }




            },
            error: function () {
                // Display error message
                alert("An error occurred while updating Database.");
            }
        });
        }

        function LoadTable ()
        {
            $.ajax({
                type: "POST",
                url: "@Url.Action("FillGRN", "Home")",
                data: {
                },
                dataType: "json",
                success: function (response) {
                    // Handle the response from the server
                    console.log(response);

                    var data = JSON.parse(response);
                    data.forEach(function (item, index) {
                        $("#branch").val(item.branch_name);
                        var td = "";
                        td = td + "<td>" + (Number(index) + 1) + "</td>";
                        td = td + "<td>" + item.item_name + "</td>";
                        td = td + "<td>" + item.Pend_Qty + "</td>";
                        td = td + "<td><input id='challan_qty" + index + "' type='text' class='challan' arg1='" + item.iBodyId + "' arg2='" + item.Pend_Qty + "' arg3='" + item.PORate + "' arg4='challan_rate" + index + "' /></td>";
                        td = td + "<td>" + item.PORate + "</td>";
                        td = td + "<td><input id='challan_rate" + index + "' type='text' /></td>";
                        $("#grnBody").append("<tr>" + td + "</tr>");
                        Totalrecord++;
                    });
                },
                error: function () {
                    // Display error message
                    alert("An error occurred while updating Database.");
                }
            });
        }
    </script>
}

VendorPortal/VendorPortal/Views/Home/PendingOrder.cshtml
@{
    ViewBag.Title = "PendingOrder";
}
<h3>Pending Order</h3>
<div class="row">
    <div class="col-md-12">
        <!--<h1>@Session["UserID"].ToString()</h1>-->
        <label>Start Date:</label>
        <input type="date" id="start_date" name="start_date">
        <label>End Date:</label>
        <input type="date" id="end_date" name="end_date">
        <label>Branch:</label>
        <select name="branch" id="branch">
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
            <option value="mercedes">Mercedes</option>
            <option value="audi">Audi</option>
        </select>
        <input type="button" id="refresh" value="Refresh" />
        <section id="loginForm">
            <table id="pendingPO" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Sr No</th>
                        <th>Vtype</th>
                        <th>Document No</th>
                        <th>Branch</th>
                        <th>Item</th>
                        <th>Pending Qty</th> 
                        <th>Select</th>                       
                    </tr>
                </thead>
                <tbody id="pendingPOBody">                                  
                    <!--<tr>
                        <td>Sr No</td>
                        <td>Vtype</td>
                        <td>Document No</td>
                        <td>Branch</td>
                        <td>Item</td>
                        <td>Pending Qty</td>
                        <td><input type="checkbox" id="vehicle1" class="ads_Checkbox" name="selector[]" value="1"></td>
                    </tr>
                    <tr>
                        <td>Sr No</td>
                        <td>Vtype</td>
                        <td>Document No</td>
                        <td>Branch</td>
                        <td>Item</td>
                        <td>Pending Qty</td>
                        <td><input type="checkbox" id="vehicle1" class="ads_Checkbox" name="selector[]" value="2"></td>
                    </tr>
                        -->
                </tbody>
            </table>
            <input type="button" id="save_value" value="Proccess" />
        </section>
    </div>
</div>

@section Scripts {

    <!--<script src="/VendorPortal/Scripts/VendorPortal.js"></script>-->
    <script type="text/javascript">
        //LoadPO();
        var Totalrecord = 0;
        var Processrecord = 0;
        $('#save_value').click(function () {
            RemoveData();

        });
        LoadBranch();
        $("#refresh").click(function () {
            LoadPO();
        });

        function RemoveData()
        {
            $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeletePO", "Home")",
                    data: {
                    },
                    dataType: "json",
                    success: function (response) {
                    // Handle the response from the server
                        console.log(response);
                        $('.ads_Checkbox:checked').each(function () {
                            //alert($(this).val());
                            //alert($(this).attr("arg1"));
                            SavePendPo($(this).attr("arg1"), $(this).attr("arg2"), $(this).attr("arg3"), $(this).attr("arg4"), $(this).attr("arg5"), $(this).val());
                            Totalrecord++;
                        });
                        //alert("Save Completed");

                },
                error: function () {
                    // Display error message
                    alert("An error occurred while updating Database.");
                }
            });
        }

        function ValidatePO()
        {
            $.ajax({
                    type: "POST",
                    url: "@Url.Action("ValidatePO", "Home")",
                    data: {
                    },
                dataType: "json",
                success: function (response) {
                    // Handle the response from the server
                    if (response.status)
                    {
                        document.location = "@Url.Action("GRNEntry", "Home")";
                        //document.location = "@Url.Action("MRNEntry", "Home")";
                    }
                    else
                    {
                        alert(response.data.message);
                    }

                },
                error: function () {
                    // Display error message
                    alert("An error occurred while updating Database.");
                }
            });
        }

        function LoadPO()
        {
            $("#pendingPOBody").html("");
            $.ajax({
                    type: "POST",
                    //url: "VendorPortal/Login",
                    //url: "@Url.Action("Login", "VendorPortal")",
                    url: "@Url.Action("GetPO", "Home")",

                    data: {
                    },
                dataType: "json",
                success: function (response) {
                    //console.log(response);

                    var data = JSON.parse(response);

                    data.forEach(function (item, index) {
                        //console.log(item, index);
                        var td = "";
                        td = td + "<td>" + (Number(index) + 1) + "</td>";
                        td = td + "<td>" + item.sAbbr + "</td>";
                        td = td + "<td>" + item.sVoucherNo + "</td>";
                        td = td + "<td>" + item.BranchName + "</td>";
                        td = td + "<td>" + item.sName + "</td>";
                        td = td + "<td>" + item.bal + "</td>";
                        td = td + "<td><input type='checkbox' id='po" + (Number(index) + 1) + "' class='ads_Checkbox' name='selector[]' arg1='" + item.sAbbr + "' arg2='" + item.sVoucherNo + "' arg3='" + item.Branch + "' arg4='" + item.iProductId + "' arg5='" + item.bal + "' value='" + item.iBodyId + "'></td>";
                        $("#pendingPOBody").append("<tr>" + td + "</tr>");
                    });

                    //console.log(data);


                },
                error: function () {
                    // Display error message
                    alert("An error occurred while updating Database.");
                }
            });
        }

        function SavePendPo(Vtype, DocNo, Branch_Id, Item_Id, Pend_Qty, IbodyId)
        {
            $.ajax({
                type: "POST",
                url: "@Url.Action("SavePendPo", "Home")",
                data: {
                    Vtype: Vtype,
                    DocNo: DocNo,
                    Branch_Id: Branch_Id,
                    Item_Id: Item_Id,
                    Pend_Qty: Pend_Qty,
                    IbodyId: IbodyId
                },
                dataType: "json",
                success: function (response) {
                    // Handle the response from the server
                    console.log(Vtype, DocNo, Branch_Id, Item_Id, Pend_Qty);
                    Processrecord++;
                    if (Totalrecord == Processrecord)
                    {
                        ValidatePO();
                    }

                },
                error: function () {
                    // Display error message
                    alert("An error occurred while updating Database.");
                }
            });
        }


        function LoadBranch()
        {
            $("#branch").html("");
            $.ajax({
                type: "POST",
                url: "@Url.Action("FillBranch", "Home")",

                data: {
                },
            dataType: "json",
            success: function (response) {
                //console.log(response);

                var data = JSON.parse(response);

                data.forEach(function (item, index) {
                    //console.log(item, index);
                    var td = "";
                    td = td + "<option value='" + item.iMasterId + "'>" + item.sName + "</option>";
                    $("#branch").append(td);
                });

                //console.log(data);


            },
            error: function () {
                // Display error message
                alert("An error occurred while updating Database.");
            }
        });
        }

        $("#btn_login").click(function ()
        {
            alert($("#user_id").val());
            alert($("#password").val());

            $.ajax({
                type: "POST",
                //url: "VendorPortal/Login",
                //url: "@Url.Action("Login", "VendorPortal")",
                url: "@Url.Action("Login", "Home")",

                data: {
                    user_name: $("#user_id").val(),
                    password: $("#password").val()
                },
                dataType: "json",
                success: function (response) {
                    // Handle the response from the server
                    alert(response.data.message);
                    //document.location = "/PendingOrder";
                    if (response.status)
                    {
                        document.location = "@Url.Action("PendingOrder", "Home")";
                    }

                },
                error: function () {
                    // Display error message
                    alert("An error occurred while updating Database.");
                }
            });


        });

    </script>
}